#!/bin/bash
#Включение отладки bash:

#запрос пароля для sudo
echo "введите логин от учетной записи"
read -a USER
echo "Введите пароль от учетной записи"
read -a PASSWD

echo "Программа выполяется.."


#Файл логов:
LOG="C-iptables.log"

#Список хостов:
HOSTS_B="192.168.1.171"
HOSTS_C="192.168.1.172"

time=$(date +%s)

#Команды для expect:
COMM="

#подключаемся к удаленному серверу
spawn ssh -o IdentitiesOnly=yes $USER@$HOSTS_C 
expect \"*(yes/no?*\" {send \"yes\r\"}
expect \"Password:\"
send \"$PASSWD\r\"


#установка iptables
expect \"*>\"
send \"sudo apt-get install iptables -y\r\"
expect \"*password*\" {send \"$PASSWD\r\"}
expect \"*>\"
send \"sudo iptables -A INPUT -s 192.168.1.157/32 -p tcp --dport 22 -j ACCEPT\r\"
expect \"*password*\" {send \"$PASSWD\r\"}
send \"sudo iptables -A INPUT -p tcp --dport 22 -j DROP\r\"
expect \"*password*\" {send \"$PASSWD\r\"}



#Завершение выполнения expect:
expect eof
"

#Запуск expect с набором команд:
expect -c "$COMM" >> $LOG

echo "время затрачено:"
echo $(($(date +%s)-$time))

#Вывод разделителя:
echo ========================================================================= >> $LOG

